### ISSUE TITLE
Implementation of the report

### ISSUE THREAD

**Issue by dachafra** [osoc-es/data-quality-madrid#12]
- [x] Given a CSV file, analyze it according to the "tips" from datos.gob.es
- [ ] Return the results of the analysis to the frontend

**Comment by rodrigosuaarez** [comment]
update: 4/15 are already implemented

**Comment by Luis15CR** [comment]
### Validaciones a realiza:
- [x] Columnas Repetidas.
- [x] Valores Desconocidos.
- [x] Tipos de datos por columna
- [x] Campos de texto.
- [x] Campos numéricos.
- [x] Campos Fecha.
- [x] Campos Teléfono
- [x] Coordenadas Geográficas.

### Validaciones que NO se harán por factor tiempo:
- [x] Estructura vertical.
- [x] Valores estandarizados.
- [x] Campos codificados.
- [ ] No totales o sub totales.
- [ ] Campos Dirección Postal.

### Others
- [x] Definición de la estructura de datos a enviar al frontend
- [x] Cálculo cuantitativo general posterior al análisis, en base a lo envíen @Sofi00 y @ednaru

**Comment by fbpazos** [comment]
All done!
