### ISSUE TITLE
Generate the report in the frontend

### ISSUE THREAD

**Issue by Jorgeelalto** [osoc-es/data-quality-madrid#15]
Decide if we are going to use some kind of library or we are just going to promt the "Save as PDF" dialog in the browser (that should work just fine).

**Comment by Jorgeelalto** [comment]
This might be useful: https://ekoopmans.github.io/html2pdf.js/

**Comment by rodrigosuaarez** [comment]
- [x] visualize the report in html in the website 
- [x] transform the report into pdf

**Comment by Jorgeelalto** [comment]
Donete
