### ISSUE TITLE
Duplicate results when querying /getDatasets

### ISSUE THREAD

**Issue by Jorgeelalto** [osoc-es/data-quality-madrid#18]
I'm getting a lot of duplicates when getting datasets with the `/getDatasets` endpoint. This is an example using datos.gob and the _Autoridad Portuaria de Cartagena_ publisher (few results, but still lots of duplicates and the same thing happens with other publishers):

![image](https://user-images.githubusercontent.com/32217459/125298907-e380d400-e328-11eb-8f33-3a9b918f879e.png)

I've been checking whether their URLs are the same and they are, this is an example:

![image](https://user-images.githubusercontent.com/32217459/125298992-fbf0ee80-e328-11eb-8701-3f7ad5167d77.png)

This could be solved in the front end but it's more efficient if it is solved in the back end.

**Comment by dachafra** [comment]
solved in the backend

**Comment by dachafra** [comment]
solved
