### ISSUE TITLE
Overall design and branding

### ISSUE THREAD

**Issue by rodrigosuaarez** [osoc-es/data-quality-madrid#7]
Comprises the front end part of the app and the presentation page. Branding, webpage contents, layouts.

- [x] Project name
- [x] Logo (?)
- [x] Colors
- [x] Fonts
- [x] Overall style for the webpages (including front end)
- [x] Generated documents style and formatting

**Comment by Jorgeelalto** [comment]
We might want to use https://getbootstrap.com

**Comment by rodrigosuaarez** [comment]
1 Name, logo 
2 button that redirects you to the app page 
3 explanationn of the project 
4 names of the creators

**Comment by Jorgeelalto** [comment]
app page:

select data set -> validate

after validation, the data is presented in HTML (and an option to download as PDF?)

**Comment by rodrigosuaarez** [comment]
Name-> Data koality 
Logo -> a koala 
we are also  going to use colours emulating a jungle, using dark greens and browns

**Comment by Jorgeelalto** [comment]
The font used in the logo is Helvetica. In the website, the default sans serif is being currently used and works well as it is usually similar enough to Helvetica.

Using default system fonts also helps in reducing website size and loading time :)

**Comment by dachafra** [comment]
done
